name: dotnet package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK 3.1.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ApplyToBecomeInternal/ApplyToBecomeInternal.sln
    - name: Build
      run: dotnet build ApplyToBecomeInternal/ApplyToBecomeInternal.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ApplyToBecomeInternal/ApplyToBecomeInternal.sln --no-restore --verbosity normal
